spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: megamart.noreply@gmail.com
    password: hkee lvye saxt obyw
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 560987570310-922lscnthmcr873opethtivq9q6ldq1j.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email

  datasource:
    url: jdbc:mysql://localhost:3306/MegaMart
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
